#macro DT (delta_time / 1000000)
#macro WAVE_WARMUP_COUNTDOWN 30
#macro WAVE_FOE_COUNTDOWN 1
#macro WAVE_COUNTDOWN 15

#macro MAX_LEVEL_INDEX 12

#macro MAX_TOWER_LEVEL 3

#macro BURN_DURATION 2
#macro BURN_DPS 2

#macro POISON_DURATION 2
#macro POISON_DPS 2

#macro SLOW_DURATION 2
#macro SLOW_FACTOR 0.5

#macro IMMOBILIZE_DURATION 1

#macro GRID_CELL_SIZE 4
#macro GRID_COLLISION_FREE 0
#macro GRID_COLLISION_FILLED 1
#macro GRID_COLLISION_PATH 2

#macro SOUND_PRIORITY_AMBIENT           100
#macro SOUND_PRIORITY_BGM               100
#macro SOUND_PRIORITY_UI                50
#macro SOUND_PRIORITY_GAMEPLAY_HIGH     40
#macro SOUND_PRIORITY_GAMEPLAY_LOW      random_range(1, 25)

#macro FIELD_WIDTH 1366
#macro FIELD_HEIGHT 768

#macro RELEASE_MODE false
#macro release:RELEASE_MODE true
#macro pi_release:RELEASE_MODE true